### ISSUE TITLE
[Feature Request] Show resolution for listed textures in VRAM calculator

### ISSUE THREAD

**Issue by Realmlist** [Thryrallo/VRC-Avatar-Performance-Tools#18]
If possible please add the current resolution per texture listed in the textures drop-down in the VRAM calculator, between the objects box and compression method perhaps.

Example:
<img width="481" alt="Untitled-1" src="https://user-images.githubusercontent.com/2737082/226547223-38129efe-97ea-4a0d-9d07-9908814f5220.png">

**Comment by Thryrallo** [comment]
done
<img width="574" alt="image" src="https://user-images.githubusercontent.com/40315315/226761440-53f5d618-1fbf-4d9b-b16b-c31e2fc929b9.png">
