### ISSUE TITLE
[VPM/VCC] VCC thinks v1.2.0 is latest version

### ISSUE THREAD

**Issue by Realmlist** [Thryrallo/VRC-Avatar-Performance-Tools#19]
VCC thinks v1.2.0 is the latest version when I add the repo through VPM.
Manually selecting the version to the *actual* latest version fixes the issue.

<img width="722" alt="image" src="https://user-images.githubusercontent.com/2737082/226562307-eefb938c-f865-4025-8a2a-e35ad2d185dc.png">

**Comment by Thryrallo** [comment]
Sure does. VCC issue, not me.
