### ISSUE TITLE
Wrong VRAM size listed for .dds texture

### ISSUE THREAD

**Issue by BlueAmulet** [Thryrallo/VRC-Avatar-Performance-Tools#21]
I wanted better DXT1 compression than what Unity provides so I compressed my textures with rgbcx (Used bc7enc in DXT1 mode)

The .dds filesize and what Unity reports is both 2.7MB, but the VRAM tool lists the texture as 5.3MB

I am using the latest version, 1.3.2

**Comment by Thryrallo** [comment]
Please test with 1.3.6

**Comment by BlueAmulet** [comment]
Appears to be working properly now, thank you.
