### ISSUE TITLE
GUI fails to draw in VRAM calculator v.1.3.4+

### ISSUE THREAD

**Issue by xMorioh** [Thryrallo/VRC-Avatar-Performance-Tools#23]
I've updated the VRAM calculator due to the .DDS bug from v.1.3.2 to v.1.3.5 but v.1.3.4 also has this issue, perhaps the error log itself already helps you enough to understand the issue ? if not then let me know what else i could provide to you to get this issue fixed.

![Unity_jRz5BxKdMe](https://github.com/Thryrallo/VRC-Avatar-Performance-Tools/assets/114238144/b268b50a-6100-488b-ae87-38a7d1516764)

Basically the GUI stops drawing after the first property line being drawn, the second texture that should be displayed in the tool would be a Normal Map, perhaps something specific with Normal Maps that's off here.

Here is a list of textures how they get ordered and show in v.1.3.2 (don't worry about the wrong file size this is fixed):
![Unity_F3eEdKzJ3c](https://github.com/Thryrallo/VRC-Avatar-Performance-Tools/assets/114238144/a9c136e8-f2f0-4b87-aa9d-baaa3341bacb)

**Comment by Thryrallo** [comment]
Please test with 1.3.6
