### ISSUE TITLE
 Version 1.3.6 Hash Mismatch

### ISSUE THREAD

**Issue by lonelyicer** [Thryrallo/VRC-Avatar-Performance-Tools#28]
VPM Provide: fbe3f74d2e8a51c5b16f4e6ffc5b036704eed0a531c245233c1a1048318c1ca5
Local Calculate: f1112d4e66f3467bd8143dc9650085b9999f0b31a34d19ae920af3f7936d1f78

**Comment by i0ntempest** [comment]
Release files were regenerated to fix #26, probably needs to update checksums

**Comment by Thryrallo** [comment]
yeah, i fucked up by overwriting the existing build. i am creating a build with a new version number and maybe delete 1.3.6
