### ISSUE TITLE
Add layer count or change anystate transition count to Layer count 

### ISSUE THREAD

**Issue by jellejurre** [Thryrallo/VRC-Avatar-Performance-Tools#9]
Benchmarks of controller runtime performance show that layer count is way more important than anystate transition count.

300 layers being ran (so 100 layers on local fx layer, 300 layers anywhere else) impacts frametime by 2.5 ms, while on the same pc, having a layer with 10000 anystate transitions didn't even manage to impact frametime by 1 ms.

**Comment by Thryrallo** [comment]
done
